http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  productsAPI:
    host: localhost
    paths: '/Api/v1/Product'
  ordersAPI:
    host: localhost
    paths: '/Api/v1/Oder'
serviceEndpoints:
  productService:
    url: 'http://localhost:3000'
  orderService:
    url: 'http://localhost:3001'
policies:
  - proxy
pipelines:
  productsPipeline:
    apiEndpoints:
      - productsAPI
    policies:
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
  ordersPipeline:
    apiEndpoints:
      - ordersAPI
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
